//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VM.Platform.TestAutomationFramework.UIAutomation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VM.Platform.TestAutomationFramework.UIAutomation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to test case repository.
        /// </summary>
        internal static string Cannot_connect_to_test_case_repository {
            get {
                return ResourceManager.GetString("Cannot_connect_to_test_case_repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password, or user does not have permission to access the repository.
        /// </summary>
        internal static string Invalid_username_or_password__or_user_does_not_have_permission_to_access_the_repository {
            get {
                return ResourceManager.GetString("Invalid_username_or_password__or_user_does_not_have_permission_to_access_the_repo" +
                        "sitory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloseAlert command must specify action - either &apos;Accept&apos; or &apos;Dismiss&apos;.
        /// </summary>
        internal static string InvalidAlertClosingAction {
            get {
                return ResourceManager.GetString("InvalidAlertClosingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page name.
        /// </summary>
        internal static string InvalidPageName {
            get {
                return ResourceManager.GetString("InvalidPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid execution parameters for the Page command.
        /// </summary>
        internal static string PageCommand_ValidateExecutionParameters_Invalid_execution_parameters_for_the_Page_command {
            get {
                return ResourceManager.GetString("PageCommand_ValidateExecutionParameters_Invalid_execution_parameters_for_the_Page" +
                        "_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiLoopVariable : key or Value not exist in the context.
        /// </summary>
        internal static string StartStopIterationCommand_StopIterationProcess_DiLoopVariable_key_or_Value_not_exist {
            get {
                return ResourceManager.GetString("StartStopIterationCommand_StopIterationProcess_DiLoopVariable_key_or_Value_not_ex" +
                        "ist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiStop: key or value not in the context.
        /// </summary>
        internal static string StartStopIterationCommand_StopIterationProcess_DiStop_key_or_Value_not_exist {
            get {
                return ResourceManager.GetString("StartStopIterationCommand_StopIterationProcess_DiStop_key_or_Value_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS test case Id must be a positive integer.
        /// </summary>
        internal static string TFS_test_case_Id_must_be_a_positive_integer {
            get {
                return ResourceManager.GetString("TFS_test_case_Id_must_be_a_positive_integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TFS Work Item Store adapter has not been initialized yet.
        /// </summary>
        internal static string TFS_Work_Item_Store_adapter_has_not_been_initialized_yet {
            get {
                return ResourceManager.GetString("TFS_Work_Item_Store_adapter_has_not_been_initialized_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid parameter(s) in:.
        /// </summary>
        internal static string ValidateExecutionParameters_Invalid_Parameter {
            get {
                return ResourceManager.GetString("ValidateExecutionParameters_Invalid_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item does not exist.
        /// </summary>
        internal static string Work_item_does_not_exist {
            get {
                return ResourceManager.GetString("Work_item_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item is not a test case.
        /// </summary>
        internal static string Work_item_is_not_a_test_case {
            get {
                return ResourceManager.GetString("Work_item_is_not_a_test_case", resourceCulture);
            }
        }
    }
}
